import datetime
import os

import requests

def getPastWeekDate(noOfDaysFromPresent):
    today = datetime.datetime.now()
    n_days_ago = today - datetime.timedelta(days=noOfDaysFromPresent)
    strDate = n_days_ago.strftime("%d-%m-%Y");
    return strDate;
    
def getTodayDate():
    today = datetime.datetime.now()
    strDate = today.strftime("%d-%m-%Y");
    return strDate;

def getTimeStamp():
    today = datetime.datetime.now()
    strDate = today.strftime("%H%M%S");
    return strDate;

def getAutoGeneratedFileName(strFileType,reportsDir):
    strDate = datetime.datetime.now().strftime("%d%m%Y_%H%M%S");
    datefolder = datetime.datetime.now().strftime("%d%m%Y");
    folderPath = reportsDir+datefolder;
    if os.path.exists(folderPath):
        print("folder already exits")
    else:
         path = os.path.join(reportsDir, datefolder)
         os.makedirs(path);
   
    fileName = reportsDir+datefolder+"//bse_"+strFileType+"_data_"+strDate;
    return fileName;

def getAutoAttachmentFileName(reportsDir):
    strDate = datetime.datetime.now().strftime("%H%M%S");
    datefolder = datetime.datetime.now().strftime("%d%m%Y");
    existingFolderPath = reportsDir+datefolder+"//"
    folderPath = existingFolderPath +strDate;
    if os.path.exists(folderPath):
        print("folder already exits")
    else:
         path = os.path.join(existingFolderPath, strDate)
         os.makedirs(path);
    fileName = existingFolderPath+strDate;
    return fileName;


def getAutoGeneratedLogFileName(strFileType):
    strDate = datetime.datetime.now().strftime("%d%m%Y_%H%M%S");
    fileName = "logs_security_wise_archive_"+strFileType+"_data_"+strDate+".log";
    return fileName;

def downloadPdf(pdf_url, filename):
    try:
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
        }

        response = requests.get(pdf_url, headers=headers)

        if response.status_code == 200:
            with open(filename, "wb") as file:
                file.write(response.content)
            print(f"PDF file '{filename}' downloaded successfully!")
        else:
            print(f"Failed to download the PDF file. Status code: {response.status_code}")
    except Exception as e:
        print(f"An error occurred: {e}")